# DEFINE ESSE APLICATION.PROPERTIES COM PADRAO
spring.profiles.active=default
# CONFIGURACOES PARA CONEXAO COM BANCO DE DADOS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.flyway.enabled=true

# JPA FAZ A TRADUCAO DE OBJ JAVA PARA SQL APROPRIADO PARA CADA BANCO (MYSQL)
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
# EXISTEM ALGUMAS CONFIGURACOES, O IDEAL E QUE SE USE 'NONE'. OS DIFERENTES DE 'NONE' N�O DEVEM SER USADOS EM PRODUCAO
# NONE: JPA NAO FAZ NADA NO SEU BANCO
# VALIDATE: VALIDA O SCHEMA
# CREATE: PODE CRIAR E PODE DELETAR DADOS
# CREATE-DROP: O BANCO E CRIADO E DELETADO A CADA SESSAO
# UPDATE: ALTERA O QUE JA SE TEM
 #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
# recomendado true apenas para debug, fora isso e desperdicio de recursos da maquina.


#CONFIGURACOES DE LOG
logging.level.br.com.erudio=DEBUG

# SWAGGER OpenAPI
springdoc.paths-to-match=/api/**/v1/**
springdoc.swagger-ui.use-root-path=true

# Propriedade que lista as origins aceitas nesta API
cors.originPatterns:https://localhost:8080,https://localhost:3000,https://lucas.teste.com

