# CONFIGURACOES PARA CONEXAO COM BANCO DE DADOS
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
        username: root
        password: root

    #jpA FAZ A TRADUCAO DE OBJ JAVA PARA SQL APROPRIADO PARA CADA BANCO (MYSQL)
    jpa:
        hibernate:
            ddl-auto:  update
                # EXISTE ALGUMAS CONFIGURACOES, O IDEAL E QUE SE USE 'NONE', O OS DIFERENTES DE NONE NAO SE DEVE USAR EM PRODUCAO
                # NONE: JPA NAO FAZ NADA NO SEWU BANDO
                # VALIDADE: VALIDA O SCHEMA
                # CREATE: PODE CRIAR E PODE DELETAR DADOS
                # CREATE-DROP: O BANCO E CRIADO E DELETADO A CADA SECAO
                # UPDATE: ALTERA O QUE JA SE TEM
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
            show-sql: false
                #recomendado true apenas para debug, fora isso eh desperdicio de recursos da maquina.


#
